export default {
    name: "joke",
    aliases: ["witz", "lachen"],
    description: "Erzählt einen zufälligen Witz",
    cooldown: 5,
    async execute(chat, msg) {
        const jokes = [
            "Ich habe einen Witz über Zeitreisen – aber der kommt erst später.",
            "Warum haben Geister so viele Freunde? Weil sie einfach durch alles hindurchsehen!",
            "Wie nennt man einen Bumerang, der nicht zurückkommt? Ein Stock!",
            "Warum können Skelette so schlecht lügen? Weil man sie durchschauen kann!",
            "Was macht ein Pirat am Computer? Er drückt die Enter-Taste!",
            "Warum ging der Pilz auf die Party? Weil er ein Champignon war!",
            "Wie nennt man einen Bumerang, der nicht zurückkommt? Ein Stock!",
            "Warum können Geister so gut schummeln? Sie sind durchsichtige Trickser!",
            "Was macht ein Keks unter einem Baum? Krümel!",
            "Was ist orange und läuft durch den Wald? Eine Wanderine!",
            "Warum haben Bienen so viel Arbeit? Weil sie den ganzen Tag am Arbeiten sind!",
            "Was ist grün und schüchtern? Ein Gurkchen!",
            "Warum ging der Frosch ins Konzert? Weil er auf die Quakenmusik stand!",
            "Was macht ein Mathematiker, wenn er Hunger hat? Er nimmt eine Zahlensuppe!",
            "Was macht ein Vampir, wenn er Durst hat? Er geht in ein Blutspendezentrum!",
            "Warum können Teddybären keine Freunde finden? Weil sie zu flauschig sind!",
            "Was ist rot und schlecht für die Zähne? Ein Ziegelstein!",
            "Warum können Computer keine guten Witze erzählen? Sie haben keinen Humor!",
            "Was ist klein, grün und dreieckig? Ein Kiwifalter!",
            "Warum können Bäume so gut schummeln? Weil sie immer im Wald sind!",
            "Was macht ein Astronom, wenn er nachts wach ist? Er beobachtet die Sterne!",
            "Wie nennt man einen Hund, der zaubern kann? Ein Labrakadabrador!",
            "Warum sind Geister immer so schlecht im Tennis? Sie haben keinen Aufschlag!",
            "Was ist weiß und kann fliegen? Ein Flugzeug mit einem weißen Anzug!",
            "Warum ging der Pilz zum Arzt? Weil er sich nicht gut fühlte!",
            "Was sagt der eine Stuhl zum anderen? Komm, wir setzen uns hin!",
            "Warum haben Computer keine Hände? Weil sie nicht klatschen können!",
            "Was ist braun und sitzt auf einem Stuhl? Ein Sessel!",
            "Warum lieben Elektriker Musik? Weil sie immer mit Strom arbeiten!",
            "Was macht ein Fisch im Computer? Er drückt die Netz-Taste!",
            "Warum haben Gummibärchen immer so gute Laune? Weil sie nie etwas zu verlieren haben!",
            "Wie nennt man einen schüchternen Bäcker? Ein Teigling!",
            "Was sagt der eine Fisch zum anderen? Nichts, Fische können nicht sprechen!",
            "Was ist schwarz und weiß und sitzt auf einem Baum? Ein Panda im Anzug!",
            "Warum können Katzen so gut singen? Weil sie immer auf den richtigen Tasten sitzen!",
            "Was macht ein Geier auf einem Flugplatz? Er wartet auf den nächsten Flug!",
            "Wie nennt man einen Bären ohne Zähne? Einen Gummibär!",
            "Was sagt der Fisch, der gegen den Strom schwimmt? 'Ich habe den Überblick verloren!'",
            "Warum haben Vögel immer so gute Laune? Weil sie den ganzen Tag im Flug sind!",
            "Was ist das Lieblingsspiel eines Taschenrechners? Mathe!",
            "Was macht ein Jäger im Wald? Er jagt den Hunden hinterher!",
            "Warum geht der Laptop nie zum Arzt? Weil er schon einen Virus hat!",
            "Was ist schwarz und weiß und läuft durch den Wald? Ein Zebra mit Schuhen!",
            "Warum können Taschenrechner keine guten Witze erzählen? Sie haben keinen Humor!",
            "Was macht ein Pirat im Fitnessstudio? Er trainiert seine Muskeln!",
            "Warum war der Mathematiker im Dschungel? Weil er eine Wurzel gesucht hat!",
            "Was ist groß, grau und steht im Wald? Ein Elefant mit einem Anzug!",
            "Warum gehen keine Vampire ins Fitnessstudio? Sie fürchten sich vor den Gewichten!",
            "Was ist grün und schüchtern? Ein Gurkchen!",
            "Warum können Bienen so gut tanzen? Weil sie den Rhythmus im Blut haben!",
            "Was ist weiß, flauschig und sitzt auf einem Baum? Ein flauschiger Eichhörnchen-Teppich!",
            "Warum können Elefanten keine Computer benutzen? Weil sie die Maus nicht finden können!",
            "Was macht ein Vögelchen in einer Bibliothek? Es liest ein Buch!",
            "Warum gehen Fische nie ins Kino? Weil sie keinen Bock auf die Filme haben!",
            "Was hat ein Känguru immer bei sich? Ein Hopp-konto!",
            "Was macht ein Pilz im Regen? Er wächst noch schneller!",
            "Warum konnte der Bäcker keine Brötchen mehr backen? Weil er das Rezept vergessen hatte!",
            "Was ist orange und dreieckig? Eine Karotte im Pilzmodus!",
            "Was ist der Unterschied zwischen einem Keks und einem Computer? Der Keks hat immer einen guten Geschmack!",
            "Was macht ein Fisch im Fitnessstudio? Er trainiert seine Flossen!",
            "Warum können Geister keine Sportler werden? Sie haben keine Muskeln!",
            "Was macht ein Elefant, wenn er auf einem Stuhl sitzt? Er wird von allen bewundert!",
            "Warum ging der Pilz auf die Party? Weil er ein Champignon war!",
            "Was ist braun und schwer zu heben? Ein Bär!",
            "Warum können Bienen keine guten Tänzer sein? Weil sie immer im Kreis tanzen!",
            "Was sagt der eine Stuhl zum anderen? 'Du bist echt unbequem!'",
            "Was ist die Lieblingsfarbe eines Chamäleons? Es hat keine, weil es sich immer anpasst!",
            "Was macht ein Hund in der Sonne? Er läuft in den Schatten!",
            "Warum können Hunde so gut die Zeit abschätzen? Weil sie einen sehr guten Hundeblick haben!",
            "Was ist weiß und schäumt? Ein Schaumstoff! ",
            "Warum können Gänse so gut fliegen? Weil sie immer den richtigen Kurs setzen!",
            "Was ist der Lieblingssport eines Bären? Bärenreiten!",
            "Warum haben Fische keine Probleme mit dem Internet? Weil sie immer im Netzwerk sind!",
            "Was ist schwarz, weiß und rot? Ein Zebra mit einem Sonnenbrand!",
            "Warum lieben Kängurus den Frühling? Weil sie dann überall hüpfen können!",
            "Was ist der Unterschied zwischen einem Tiger und einem Löwen? Der Tiger ist gestreift, der Löwe hat Mähne!",
            "Was ist der Lieblingssport eines Bären? Eisbaden!",
            "Warum gehen Vögel immer in den Süden? Weil es dort immer warm ist!",
            "Was macht ein Löffel im Restaurant? Er isst das Essen!",
            "Warum können Ratten keine Bücher lesen? Sie haben keine Ahnung von Literatur!",
            "Was ist schwarz und weiß und rennt durch den Wald? Ein Zebra auf der Flucht!",
            "Warum haben Pilze immer so gute Laune? Weil sie immer mit den richtigen Leuten abhängen!",
            "Was macht ein Maulwurf unter der Erde? Er arbeitet als Bauarbeiter!",
            "Was ist die Lieblingszahl eines Nerds? Die Zahl Pi!",
            "Warum können Hunde keine Schach spielen? Weil sie die Regeln nicht verstehen!",
            "Was ist der Lieblingsmonat eines Abenteurers? April!",
            "Was ist die Lieblingsmusik eines Elektrikers? Strom- und Kabel-Sounds!",
            "Warum haben Pinguine so viel Spaß? Weil sie immer rutschen können!",
            "Was sagt der eine Fisch zum anderen? 'Lass uns abtauchen!'",
            "Was macht ein Vogel auf einer Tastatur? Er tippt seine Nachrichten!",
            "Warum können Pinguine keine Flugzeuge fliegen? Weil sie keine Flugerlaubnis haben!",
            "Was ist der Lieblingsdrink eines Superhelden? Super-Cola!",
            "Warum können Löwen keine Computerspiele spielen? Weil sie immer in den Wald gehen!",
            "Was ist schwarz und gelb und summt? Ein Bienenschwarm mit WLAN!",
            "Warum können Fische nicht tanzen? Sie haben keinen Rhythmus!",
            "Was ist weiß und geht immer nach oben? Ein fliegendes Ei!",
            "Warum können Eisbären keine Handys benutzen? Weil sie immer kalt werden!",
            "Was sagt der eine Apfel zum anderen? 'Ich habe die Frucht in mir!'",
            "Was macht ein Fisch in der Diskothek? Er schwimmt durch die Tanzfläche!",
            "Warum haben Wale keine Taschen? Weil sie immer alles verschlucken!",
            "Was ist weiß und schnell? Ein Schimmel auf der Rennbahn!",
            "Warum gingen die Bienen auf den Ball? Weil sie die Tanzfläche zum Summen brachten!"
        ];

        const joke = jokes[Math.floor(Math.random() * jokes.length)];
        chat.say(msg.channelName, `@${msg.displayName}, ${joke} LO);
    }
};
